drop table if exists FILM_GENRES;

drop table if exists FILM_LIKES;

drop table if exists FILMS;

drop table if exists FRIENDS_LIST;

drop table if exists GENRE;

drop table if exists MPA;

drop table if exists USERS;


CREATE TABLE IF NOT EXISTS users
(
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(255) NOT NULL UNIQUE,
    login    varchar(50)  ,
    name     varchar(255) NOT NULL,
    birthday date         NOT NULL
);

CREATE TABLE IF NOT EXISTS friends_list
(
    user_id   integer,
    friend_id integer,
    PRIMARY KEY (user_id, friend_id)

);

CREATE TABLE IF NOT EXISTS mpa
(
    mpa_rating_id INTEGER PRIMARY KEY NOT NULL,
    name          VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre
(
    genre_id INTEGER PRIMARY KEY NOT NULL ,
    name     VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    film_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar(255) NOT NULL,
    description   varchar(255),
    releaseDate   date         ,
    duration      integer not null,
    mpa_rating_id integer not null
);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  integer NOT NULL,
    genre_id integer NOT NULL,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS film_likes
(
    user_id integer NOT NULL,
    film_id integer NOT NULL,
    PRIMARY KEY (user_id, film_id)
);

ALTER TABLE friends_list
    ADD CONSTRAINT fk_friends_list_friend_id FOREIGN KEY (friend_id) REFERENCES users (user_id) ON DELETE CASCADE;

ALTER TABLE friends_list
    ADD CONSTRAINT fk_friends_list_user_id FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;

ALTER TABLE films
    ADD CONSTRAINT fk_mpa_id FOREIGN KEY (mpa_rating_id) REFERENCES mpa (mpa_rating_id) ON DELETE RESTRICT;

ALTER TABLE film_genres
    ADD CONSTRAINT fk_film_id FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE;

ALTER TABLE film_genres
    ADD CONSTRAINT fk_genre_id FOREIGN KEY (genre_id) REFERENCES genre (genre_id) ON DELETE CASCADE;

ALTER TABLE film_likes
    ADD CONSTRAINT fk_film_likes_film_id FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE;

ALTER TABLE film_likes
    ADD CONSTRAINT fk_film_likes_user_id FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;


insert into mpa (mpa_rating_id, name)
values (1, 'G'),
       (2, 'PG'),
       (3, 'PG-13'),
       (4, 'R'),
       (5, 'NC-17');

insert into genre (genre_id, name)
values (1, 'Комедия'),
       (2, 'Драма'),
       (3, 'Мультфильм'),
       (4, 'Триллер'),
       (5, 'Документальный'),
       (6, 'Боевик');
